export const Roles = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
} as const;

export type RoleType = keyof typeof Roles;

export const Permissions = {
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  EDIT_WORKSPACE: "EDIT_WORKSPACE",
  MANAGE_WORKSPACE_SETTINGS: "MANAGE_WORKSPACE_SETTINGS",

  ADD_MEMBER: "ADD_MEMBER",
  CHANGE_MEMBER_ROLE: "CHANGE_MEMBER_ROLE",
  REMOVE_MEMBER: "REMOVE_MEMBER",

  CREATE_PROJECT: "CREATE_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",

  CREATE_TASK: "CREATE_TASK",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",
  MANAGE_TASK_RELATIONS: "MANAGE_TASK_RELATIONS",

  CREATE_COMMENT: "CREATE_COMMENT",
  EDIT_COMMENT: "EDIT_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",

  UPLOAD_FILE: "UPLOAD_FILE",
  DELETE_FILE: "DELETE_FILE",

  MANAGE_NOTIFICATION_SETTINGS: "MANAGE_NOTIFICATION_SETTINGS",
  EDIT_PROFILE: "EDIT_PROFILE",

  TRACK_TIME: "TRACK_TIME",
  VIEW_TIMESHEETS: "VIEW_TIMESHEETS",
  MANAGE_TIME_ENTRIES: "MANAGE_TIME_ENTRIES",
  MANAGE_CAPACITY: "MANAGE_CAPACITY",

  EXPORT_DATA: "EXPORT_DATA",
  VIEW_AUDIT_LOG: "VIEW_AUDIT_LOG",
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_POLICIES: "MANAGE_POLICIES",

  VIEW_ONLY: "VIEW_ONLY",
} as const;

export type PermissionType = keyof typeof Permissions;
